# statistics

In [1]:
# it is the science of collecting , organizing and analyzing data

In [2]:
# data - facts or information 


In [3]:
#  types

# descriptive stats
# inferential stats

In [4]:
#  types

# descriptive stats
# inferential stats

In [5]:
# descriptive stats

# measure of central tendcy
# mean , mode , medn

# measur of disprsn
# std dev , var

# cov , correlatn , multicollnrty
# percentile , quantile 

# box plot (five numbr summary)
# outlier

# data distribution
# normal distribution
# pmf , cdf

In [6]:
# infr stats

# hypothesis testing
# z - test
# t - test
# chi square test
# anova test

In [7]:
# data gathering 

# data preprocessing

# null values
# fillna() , ffill() , bfill()
# random sample imputation
# knn imputer

# outliers
# percentile , quartile
# box plot
# five number summary
# z score 

# feature selection
# correlation
# variance inflation factor - vif (mulitcollnrty)
# chi square test (cat vs cat)
# anova test   (num vs cat)
# pca
# random forest


# handling catagorcl values
# label encoder
# ordinal encoder
# one hot encoding
# dummy variables


In [8]:
# data scnce

# matrix (1-d , 2-d , 3-d)
# dot product

# linear algebra (line equation)

# differentiation

# probability

# maxima , minima

In [9]:
# descriptive 

In [10]:
# desc -  it has a finite no of possible values that can not be divided into smaller parts
# can we measure data - no
# can we count data - yes



# cont - it is an infinite number of possible values within a time interval, the values can be divide into samaller prts 
# can we meas - yes 

# wind speed
# time taken by prject to complete
# time to wake up

In [11]:
import numpy as np
import pandas as pd

In [12]:
# mean / avg

In [13]:
x = [90, 94, 53, 68, 79, 94, 53, 65, 87, 90, 70, 69, 65, 89, 85, 53, 47, 61, 27, 80]

m = sum(x)/len(x)
m

70.95

In [14]:
a = np.array(x)
a

array([90, 94, 53, 68, 79, 94, 53, 65, 87, 90, 70, 69, 65, 89, 85, 53, 47,
       61, 27, 80])

In [15]:
np.mean(x)

70.95

In [16]:
np.average(x)

70.95

In [17]:
s = pd.Series(a)
s.mean()

70.95

In [18]:
# median

In [19]:
x = [20,10,14,24,15,26,17,19,12] 
x

[20, 10, 14, 24, 15, 26, 17, 19, 12]

In [20]:
x.sort()

In [21]:
x

[10, 12, 14, 15, 17, 19, 20, 24, 26]

In [22]:
a = np.array(x)
a

array([10, 12, 14, 15, 17, 19, 20, 24, 26])

In [23]:
np.median(a)

17.0

In [24]:
x = [20,10,14,24,15,26,17,19,12,21] 
x

[20, 10, 14, 24, 15, 26, 17, 19, 12, 21]

In [25]:
x.sort()
x

[10, 12, 14, 15, 17, 19, 20, 21, 24, 26]

In [26]:
a = np.array(x)
a

array([10, 12, 14, 15, 17, 19, 20, 21, 24, 26])

In [27]:
np.median(a)

18.0

In [28]:
x = [10, 12, 14, 15, 16, 19, 20, 21, 24,28]
x.sort()
a = len(x)

if a%2!=0:
    m = a//2
    print(x[m])
else:
    m = a//2
    s = x[m] + x[m-1]
    print(s/2)

17.5


In [29]:
a = np.array(x)
a

array([10, 12, 14, 15, 16, 19, 20, 21, 24, 28])

In [30]:
np.median(a)

17.5

In [31]:
# mode - most frequent value

In [32]:
import pandas as pd

In [33]:
l = [2,3,3,4,5,5,5,6,8,8,8,8,10]
l

[2, 3, 3, 4, 5, 5, 5, 6, 8, 8, 8, 8, 10]

In [34]:
s = pd.Series(l)
s

0      2
1      3
2      3
3      4
4      5
5      5
6      5
7      6
8      8
9      8
10     8
11     8
12    10
dtype: int64

In [35]:
s.mode()

0    8
dtype: int64

In [36]:
l = [3,3,5,5,5,6,8,8]
d = {}

for i in l:
    d[i] = l.count(i)
d

for i , j in d.items():
    if j == max(d.values()):
        print(i,"----",j)

5 ---- 3


In [37]:
d

{3: 2, 5: 3, 6: 1, 8: 2}

In [38]:
a = 8
b = 5

if a>b:
    print("a is grtr")
else:
    print("b is grtr")

a is grtr


In [39]:
# and , or

In [40]:
a = 10
b = 20

In [41]:
10>15 and b>7

False

In [42]:
10>15 or b>7

True

In [43]:
# measure of dispersion

In [44]:
import pandas as pd
import numpy as np

In [45]:
l = [2,3,3,4,5,6,7,9,11]
l

[2, 3, 3, 4, 5, 6, 7, 9, 11]

In [ ]:
a =np.array(l)
a

In [ ]:
df = pd.DataFrame(l)
df

In [ ]:
np.var(a)

In [ ]:
np.std(a)

In [ ]:
df[0].var()

In [ ]:
df.std()

In [ ]:
np.mean(a)

In [ ]:
m = df.mean()

In [ ]:
m

In [ ]:
df

In [ ]:
x = 0
for i in df[0]:
    x = x + (i-m)**2
x

In [ ]:
x/8

In [ ]:
m

In [ ]:
df.columns = ["x"]

In [ ]:
df["x-m"] = 0

In [ ]:
m

In [ ]:
df

In [ ]:
for i in df.index:
    df["x-m"][i] = df["x"][i] - m
df

In [ ]:
df["x-ms"] = 0

In [ ]:
df

In [ ]:
for i in df.index:
    df["x-ms"][i] = (df["x-m"][i])**2
df

In [ ]:
(df["x-ms"].sum()/9)**.5

# hypothesis testing

In [ ]:
# a random sample of size 20 from a population gives sample mean of 42and sample std dev of 6
# test hypothesis that the population mean is 44

# alpha 5% -> 0.05

In [ ]:
# h0 : u = 44
# ha : u != 44

In [ ]:
n = 20
sm = 42
sstd = 6
pp = 44

In [ ]:
tc = (42-44)/(6/20**.5)
tc

In [ ]:
df = 19

In [ ]:
tstats = 2.09

In [ ]:
if tstats>tc:
    print("accpt null hypothesis")
else:
    print("reject null hypothesis")

In [ ]:
# p - value

In [ ]:
l = [183, 152, 178, 157, 194, 163, 144, 114, 178, 152, 118, 158, 172, 138]


In [ ]:
pm = 165

In [ ]:
import numpy as np

In [ ]:
sm = np.array(l).mean()

In [ ]:
sm

In [ ]:
sd = np.array(l).std()
sd = 23.4
sd

In [ ]:
n = 14

In [ ]:
tc = (157-165)/(23.4/n**.5)
tc

In [ ]:
tstats = 2.1

# t test

In [ ]:
sys_bp=[183, 152, 178, 157, 194, 163, 144, 114, 178, 152, 118, 158, 172, 138]


mu=165


from scipy import stats

t_value,p_value=stats.ttest_1samp(sys_bp,mu)

one_tailed_p_value=float("{:.6f}".format(p_value/2)) # Since alternative hypothesis is one tailed, We need to divide the p value by 2.

print('Test statistic is %f'%float("{:.6f}".format(t_value)))

print('p-value for one tailed test is %f'%one_tailed_p_value)

alpha = 0.05

if one_tailed_p_value<=alpha:
  print('Conclusion','n','Since p value(=%f)'%p_value,'<','alpha(=%.2f)'%alpha,'''We reject the null hypothesis H0. So we conclude that there is no significant mean difference in systolic blood pressure. i.e., μ = 165 at %.2f level of significance'''%alpha)

else:
  print('Conclusion','n','Sincep-value(=%f)'%one_tailed_p_value, '>', 'alpha(=%.2f)'%alpha,'We do not reject the null hypothesis H0.')

In [ ]:
p<alpha

In [ ]:
a  b   c
2  3   4 
4  5   6
6  7   8

In [ ]:
42000
p1 ,p2 ,p3 ,p4

In [ ]:
10500 - p1
10500 - p2
10500 - p3
10500 - p4

In [ ]:
p1  p2   p3  
2   3   4    
4   5   6    
6   7   8    

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("case_study2.xlsx")
df.head()

In [ ]:
p1 - 12000
p2 - 12000
p3 - 12000
p4 - 12000

In [ ]:
x     aprv_flag

1       p1
2       p1
9       p1
4       p2
2       p2
5       p2
6       p1
7       p2
2       p2
8       p1

In [ ]:
p2   p1
5    1
2    2
7    9
2    6
4    8

In [ ]:
5.5  5.5

In [ ]:
# data pre processing

In [ ]:
# data gathering 

# data preprocessing

# null values
# fillna() , ffill() , bfill()
# random sample imputation
# knn imputer

# outliers
# percentile , quartile
# box plot
# five number summary
# z score 

# feature selection
# correlation
# variance inflation factor - vif (mulitcollnrty)
# chi square test (cat vs cat)
# anova test   (num vs cat)
# pca
# random forest


# handling catagorcl values
# label encoder
# ordinal encoder
# one hot encoding
# dummy variables


In [ ]:
# how to reverse without slicing

In [ ]:
s = "arun dabral"