In [2]:
import numpy as np
# pip install numpy

In [2]:
# list 
x=[1,2,3,4,5]
x

[1, 2, 3, 4, 5]

In [3]:
type(x)

list

In [6]:
# x+4

# give error

In [5]:
x*3
# does not multiply numbers.

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [7]:
"abhishek"*3

'abhishekabhishekabhishek'

In [8]:
[4,5,6]+[2]

[4, 5, 6, 2]

In [14]:
# NumPy Arrays

a = np.array(x)
print(a)

[1 2 3 4 5]


In [15]:
type(a)

numpy.ndarray

In [16]:
a+3

array([4, 5, 6, 7, 8])

In [17]:
a-3

array([-2, -1,  0,  1,  2])

In [18]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [19]:
# arange -> work like range 

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# linspace()
# Creates equally spaced numbers.

np.linspace(1,10,5)

# start = 1
# end = 10
# total numbers = 5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
# ones()
# Creates array filled with 1.

np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
# 2d 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
# zeros()
# Creates array of 0.

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# zeros()
# Creates array of 0.

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# identity()
# Also creates square identity matrix.

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# Random Numbers
# rand()
# Random decimal numbers

np.random.rand()

0.37090595825674944

In [29]:
# 2d
np.random.rand(4,4)

array([[0.50625722, 0.62886398, 0.46630326, 0.14578251],
       [0.40229011, 0.54079994, 0.87257847, 0.45675739],
       [0.98751796, 0.78059076, 0.03867209, 0.22887527],
       [0.25155939, 0.55117689, 0.29660571, 0.2169209 ]])

In [30]:
# randint()
# Random integers.

np.random.randint(1,10)

4

In [31]:
# five random number
np.random.randint(1,40,5)

array([36, 35, 36, 31,  2])

In [32]:
np.random.randint(1,40,(4,5))

# Means
# 4 rows
# 5 columns

array([[ 7, 23, 23,  6,  2],
       [ 4,  5, 35, 39, 29],
       [35,  2, 39, 35, 16],
       [13,  9, 36, 37, 35]])

In [33]:
#  Array Properties

a=np.array([[1,2,3],[4,5,6]])

In [35]:
# ndim
# Number of dimensions.

a.ndim

2

In [37]:
# shape
# Rows and columns.
a.shape

(2, 3)

In [38]:
# size
# Total elements.
a.size

6

In [44]:
# Reshape
# Changes shape of array.

p = np.arange(1,10)
p

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# Convert into
p.reshape(3,3)

# Rule:

# rows × columns = total elements

# Example

# 12 elements

# Possible shapes

# 6×2
# 4×3
# 3×4
# 2×6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Indexing
# 1D Indexing
a1 = np.array([10,20,30,40])
a1

array([10, 20, 30, 40])

In [8]:
a1[0]


40

In [5]:
a1[-1]

40

In [7]:
# 2D Indexing

x= np.random.randint(1,40,(3,3))
x

array([[14, 24, 18],
       [28,  6, 10],
       [20, 34, 35]])

In [8]:
x[1][1]

6

In [12]:
x[2][0]

20

In [13]:
# rows                      columns 
# start:stop:step ,   start:stop:step

In [15]:
x=np.arange(100).reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
x[6:,4:]

array([[64, 65, 66, 67, 68, 69],
       [74, 75, 76, 77, 78, 79],
       [84, 85, 86, 87, 88, 89],
       [94, 95, 96, 97, 98, 99]])

In [24]:
x[[0,1,9,6],[0,1,9,5]]

array([ 0, 11, 99, 65])

In [26]:
x[3:,5]

array([35, 45, 55, 65, 75, 85, 95])

In [18]:
# Advance Indexing 
x=np.array([1,2,3,4,5,6,6])
x[[0,3,5]]

# Returns

# 0th

# 3rd

# 5th elements.

# You can pick multiple indexes together.

array([1, 4, 6])

In [19]:
# Arithmetic Operations

x+2
# Adds 2 to every element.

array([3, 4, 5, 6, 7, 8, 8])

In [20]:
x-2
# Subtracts.

array([-1,  0,  1,  2,  3,  4,  4])

In [21]:
x*2
# multiply

array([ 2,  4,  6,  8, 10, 12, 12])

In [23]:
x/2
# division
# same as power and floor division

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3. ])

In [3]:
# Mathematical Functions
x= np.array([1,45,32,44,66])
x


array([ 1, 45, 32, 44, 66])

In [25]:
np.min(x)

1

In [26]:
np.max(x)

66

In [4]:
np.sum(x)

np.int64(188)

In [5]:
np.log(x)

array([0.        , 3.80666249, 3.4657359 , 3.78418963, 4.18965474])

In [6]:
np.sqrt(x)

array([1.        , 6.70820393, 5.65685425, 6.63324958, 8.1240384 ])

In [7]:
np.square(x)

array([   1, 2025, 1024, 1936, 4356])

In [8]:
np.exp(x)

array([2.71828183e+00, 3.49342711e+19, 7.89629602e+13, 1.28516001e+19,
       4.60718663e+28])

In [10]:
# funtions on axix like sum , min, max etc
x=np.random.randint(1,30,(3,3))
x

array([[ 5, 27, 18],
       [24, 29, 22],
       [26,  7, 25]], dtype=int32)

In [11]:
x.max(axis=0) #columnwise

array([26, 29, 25], dtype=int32)

In [12]:
x.max()

np.int32(29)

In [13]:
x.min(axis=1) #rowwise

array([ 5, 22,  7], dtype=int32)

In [14]:
x.sum(axis=0)

array([55, 63, 65])

In [15]:
# operations between 1D arrays

In [16]:
x=np.random.randint(1,30,6)
x

array([18,  6, 14, 16, 27, 27], dtype=int32)

In [17]:
y=np.random.randint(1,30,6)
y

array([23, 10, 16, 19, 12,  7], dtype=int32)

In [18]:
x+y

array([41, 16, 30, 35, 39, 34], dtype=int32)

In [19]:
x-y

array([-5, -4, -2, -3, 15, 20], dtype=int32)

In [20]:
np.add(x,y)

array([41, 16, 30, 35, 39, 34], dtype=int32)

In [22]:
np.multiply(x,y)

array([414,  60, 224, 304, 324, 189], dtype=int32)

In [24]:
np.subtract(y,x)

array([  5,   4,   2,   3, -15, -20], dtype=int32)

In [25]:
x*y

array([414,  60, 224, 304, 324, 189], dtype=int32)

In [26]:
x//y

array([0, 0, 0, 0, 2, 3], dtype=int32)

In [27]:
x**y

array([  -58720256,    60466176,  2105606144,           0, -1953380655,
        1870418611], dtype=int32)

In [28]:
# operation between 2D array

In [29]:
x=np.random.randint(1,50,(3,3))
x

array([[11, 11,  1],
       [22, 35, 18],
       [37,  9, 28]], dtype=int32)

In [30]:
y=np.random.randint(1,80,(3,3))
y

array([[27, 31,  8],
       [12, 29, 75],
       [15, 72, 67]], dtype=int32)

In [32]:
np.add(x,y)

array([[38, 42,  9],
       [34, 64, 93],
       [52, 81, 95]], dtype=int32)

In [33]:
x*y

array([[ 297,  341,    8],
       [ 264, 1015, 1350],
       [ 555,  648, 1876]], dtype=int32)

In [34]:
x-y

array([[-16, -20,  -7],
       [ 10,   6, -57],
       [ 22, -63, -39]], dtype=int32)

In [37]:
y//x

array([[2, 2, 8],
       [0, 0, 4],
       [0, 8, 2]], dtype=int32)

In [42]:
# Matrix Multiplication using @ -> multiple rows x column

x=np.random.randint(1,30,(2,2))
x

array([[24, 16],
       [24, 17]], dtype=int32)

In [43]:
y=np.random.randint(1,30,(2,2))
y

array([[ 4, 23],
       [ 4,  5]], dtype=int32)

In [44]:
x@y

array([[160, 632],
       [164, 637]], dtype=int32)

In [45]:
x=np.random.randint(1,100,(2,3))
y=np.random.randint(1,100,(3,2))

In [46]:
x

array([[47, 42, 11],
       [19, 57, 30]], dtype=int32)

In [47]:
y

array([[79, 18],
       [34, 54],
       [29, 35]], dtype=int32)

In [48]:
x@y

array([[5460, 3499],
       [4309, 4470]], dtype=int32)

In [ ]:
# dot product possible ?

# m1 -> r1 x c1
# m2 -> r2 x c2

# c1 == r2  

# output ->  r1 x c2
# np.dot(a,b)

In [49]:
# types of loops in np
# basic loop
# nditer
# ndenumerate

In [51]:
# basic loop

x=np.random.randint(1,30,10)
x

array([13, 21, 22, 18, 29, 25, 23, 16,  9, 20], dtype=int32)

In [52]:
for i in x:
    print(i)

13
21
22
18
29
25
23
16
9
20


In [53]:
x=np.random.randint(1,30,(3,3))
x

array([[ 8, 12, 24],
       [ 5,  1,  5],
       [26, 21, 19]], dtype=int32)

In [54]:
for i in x:
    for j in i:
        print(j)
        

8
12
24
5
1
5
26
21
19


In [55]:
x = np.random.randint(1,30,(2,3,3))
x

array([[[ 7, 18,  7],
        [27, 18, 21],
        [25, 19, 15]],

       [[ 2,  7,  1],
        [ 5,  4, 14],
        [21,  5,  3]]], dtype=int32)

In [56]:
for i in x:
    for j in i:
        for k in j:
            print(k)

7
18
7
27
18
21
25
19
15
2
7
1
5
4
14
21
5
3


In [66]:
# np.nditer()

# nditer stands for N-Dimensional Iterator.

# It iterates through every element of the array, regardless of its dimensions.

x=np.random.randint(1,30,(3,3))
x

# np.nditer() always returns one element at a time.

array([[19,  9, 21],
       [ 5,  1, 11],
       [ 9, 24,  7]], dtype=int32)

In [67]:
for i in np.nditer(x):
    print(i)

19
9
21
5
1
11
9
24
7


In [68]:
# np.ndenumerate()

# ndenumerate() returns both the index and the value of each element.

x=np.random.randint(1,30,(3,3))
x

array([[12,  4,  9],
       [ 3, 26, 10],
       [26, 24, 19]], dtype=int32)

In [69]:
for index , value in np.ndenumerate(x):
    print(index, "->",value)

(0, 0) -> 12
(0, 1) -> 4
(0, 2) -> 9
(1, 0) -> 3
(1, 1) -> 26
(1, 2) -> 10
(2, 0) -> 26
(2, 1) -> 24
(2, 2) -> 19


In [70]:
x=np.random.randint(1,100,(2,3,3))
x

array([[[26, 95, 49],
        [46, 83,  5],
        [95, 69, 96]],

       [[88, 97, 85],
        [21, 18,  5],
        [55, 27, 31]]], dtype=int32)

In [76]:
for i , j in np.ndenumerate(x):
  print(i,"->",j)

(0, 0, 0) -> 26
(0, 0, 1) -> 95
(0, 0, 2) -> 49
(0, 1, 0) -> 46
(0, 1, 1) -> 83
(0, 1, 2) -> 5
(0, 2, 0) -> 95
(0, 2, 1) -> 69
(0, 2, 2) -> 96
(1, 0, 0) -> 88
(1, 0, 1) -> 97
(1, 0, 2) -> 85
(1, 1, 0) -> 21
(1, 1, 1) -> 18
(1, 1, 2) -> 5
(1, 2, 0) -> 55
(1, 2, 1) -> 27
(1, 2, 2) -> 31


In [78]:
x=np.random.randint(1,200,(3,3))
x

array([[ 15,  63, 168],
       [161, 127, 103],
       [ 68,   7,  19]], dtype=int32)

In [79]:
for i in range(len(x)):
   for j in range(len(x[i])):
      print(i,",",j, "->",x[i][j])

0 , 0 -> 15
0 , 1 -> 63
0 , 2 -> 168
1 , 0 -> 161
1 , 1 -> 127
1 , 2 -> 103
2 , 0 -> 68
2 , 1 -> 7
2 , 2 -> 19


In [81]:
# find sum of diagonal of matrix

x=np.random.randint(1,30,(3,3))
x                  

array([[23,  6,  1],
       [18,  4,  7],
       [ 6,  4, 28]], dtype=int32)

In [82]:
sum=0
for i, j in np.ndenumerate(x):
    if i[0]==i[1]:
        sum=sum+j
print(sum)
        

55


In [83]:
# argmin - return index of min element
# argmax - return index of max element

In [84]:
x=np.random.randint(1,30,(3,3))
x

array([[25,  3, 28],
       [15, 21, 19],
       [10, 14,  1]], dtype=int32)

In [86]:
x.argmin()

np.int64(8)

In [89]:
x=np.random.randint(1,30,6)
x

array([ 9, 14, 10, 29, 26, 19], dtype=int32)

In [90]:
x.argmin()

np.int64(0)

In [91]:
x.argmax()

np.int64(3)

In [92]:
x=np.random.randint(1,30,(3,3))
x

array([[17, 21,  5],
       [27, 19, 14],
       [28,  8,  1]], dtype=int32)

In [93]:
x.argmax(axis=0)

array([2, 0, 1])

In [94]:
x.argmin(axis=1)

array([2, 2, 2])