# numpy 

In [2]:
import numpy as np

In [108]:
# pip install numpy

In [3]:
x = [2,3,4,5,7]
x

[2, 3, 4, 5, 7]

In [41]:
type(x)

list

In [43]:
x+4

TypeError: can only concatenate list (not "int") to list

In [45]:
x*2

[2, 3, 4, 5, 7, 2, 3, 4, 5, 7]

In [47]:
"hello"*3

'hellohellohello'

In [53]:
[4,5,6] + [2]

[4, 5, 6, 2]

In [31]:
a = np.array(x)

In [33]:
a

array([2, 3, 4, 5, 7])

In [35]:
type(a)

numpy.ndarray

In [55]:
a+3

array([ 5,  6,  7,  8, 10])

In [57]:
a-3

array([-1,  0,  1,  2,  4])

In [59]:
a/3

array([0.66666667, 1.        , 1.33333333, 1.66666667, 2.33333333])

In [63]:
# array()
# arange()
# linspace()
# ones()
# eye()
# identity()
# zeros()


In [69]:
x = [2,3,4,5,7]
a = np.array(x)
a

array([2, 3, 4, 5, 7])

In [71]:
type(a)

numpy.ndarray

In [75]:
a.ndim

1

In [77]:
a.shape

(5,)

In [79]:
a.size

5

In [98]:
x = [[2,3,4],[5,9,7] , [1,2,3]]
a = np.array(x)
a

array([[2, 3, 4],
       [5, 9, 7],
       [1, 2, 3]])

In [100]:
a.ndim

2

In [102]:
# no of rows x no of columns

a.shape

(3, 3)

In [104]:
a.size

9

In [116]:
x = [[2,3,4],[5,9,7]]
a = np.array(x)
a

array([[2, 3, 4],
       [5, 9, 7]])

In [118]:
a.shape

(2, 3)

In [124]:
x = [[2,3],[5,9],[4,3]]
a = np.array(x)
a

array([[2, 3],
       [5, 9],
       [4, 3]])

In [141]:
x = [[[2,3],[5,9]],[[2,3],[5,9]],[[4,3],[8,8]]]
a = np.array(x)
a

array([[[2, 3],
        [5, 9]],

       [[2, 3],
        [5, 9]],

       [[4, 3],
        [8, 8]]])

In [146]:
a.ndim

3

In [144]:
a.shape

(3, 2, 2)

In [148]:
# reshape 

In [150]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [168]:
a = np.arange(1,13).reshape(6,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [177]:
# 50 equal parts

In [1]:
x = np.linspace(1,10)
x

NameError: name 'np' is not defined

In [2]:
x = np.linspace(1,100,15)
x

NameError: name 'np' is not defined

In [216]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [220]:
a = np.ones((3,4) , dtype = int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [222]:
a = np.zeros((3,4) , dtype = int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [251]:
a = np.eye(2,5 , dtype = int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [247]:
# square

In [249]:
a = np.identity(5 , dtype = int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [260]:
# random module

# rand()
# randint()

In [270]:
x = np.random.rand()
x

0.46806763085015

In [278]:
x = np.random.rand(4,4)
x

array([[0.72996915, 0.53262129, 0.53328122, 0.72765166],
       [0.23631055, 0.14064373, 0.19185553, 0.26746833],
       [0.20821532, 0.71971598, 0.01007512, 0.02878299],
       [0.30187729, 0.39635935, 0.75422165, 0.77676416]])

In [319]:
x = np.random.randint(50,100)
x

78

In [349]:
x = np.random.randint(1,100,5)
x

array([60, 36, 94, 82, 82])

In [386]:
x = np.random.randint(1,40,(4,5))
x

array([[39, 26, 37,  2, 30],
       [33,  6, 23, 32, 27],
       [ 3, 37,  1, 29, 16],
       [ 8,  7,  1, 12, 12]])

In [46]:
x = np.random.randint(1,40,(2,3))
x

array([[31,  6, 17],
       [17, 38,  2]])

In [34]:
x.ndim

3

In [36]:
x.shape

(4, 2, 3)

In [58]:
x = np.array([10,60,30,40])

a = np.diag(x )
a

array([[10,  0,  0,  0],
       [ 0, 60,  0,  0],
       [ 0,  0, 30,  0],
       [ 0,  0,  0, 40]])

In [69]:
# indexing

In [71]:
x = [2,3,4,1,5,7,9]
a = np.array(x)
a

array([2, 3, 4, 1, 5, 7, 9])

In [73]:
a[0]

2

In [75]:
a[-1]

9

In [77]:
a[2:7]

array([4, 1, 5, 7, 9])

In [97]:
x = np.random.randint(1,30,(4,3))
x

array([[ 6, 14, 10],
       [17,  9, 17],
       [28, 11, 10],
       [14, 24, 25]])

In [111]:
x[0][2]

10

In [105]:
x[1][1]

9

In [109]:
x[2][0]

28

In [115]:
#      rows                 columns
# start : stop :step  , start : stop : step

In [5]:
x = np.arange(100).reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [6]:
x[7: ,[2,6,8]]

array([[72, 76, 78],
       [82, 86, 88],
       [92, 96, 98]])

In [125]:
x[[1,2,4],4:]

array([[14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29],
       [44, 45, 46, 47, 48, 49]])

In [123]:
x[1:5, 6:9]

array([[16, 17, 18],
       [26, 27, 28],
       [36, 37, 38],
       [46, 47, 48]])

In [121]:
x[3: ,4:]

array([[34, 35, 36, 37, 38, 39],
       [44, 45, 46, 47, 48, 49],
       [54, 55, 56, 57, 58, 59],
       [64, 65, 66, 67, 68, 69],
       [74, 75, 76, 77, 78, 79],
       [84, 85, 86, 87, 88, 89],
       [94, 95, 96, 97, 98, 99]])

In [13]:
# advance indexing

In [149]:
x = np.random.randint(1,30,7)
x

array([ 9, 20, 18,  4, 17,  2, 19])

In [163]:
x[[0,5,6]]

array([ 9,  2, 19])

In [159]:
x[[0,3,5]]

array([9, 4, 2])

In [157]:
x[::2]

array([ 9, 18, 17, 19])

In [165]:
x = np.arange(1,17).reshape(4,4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [180]:
x[[0,2,2,1],[1,1,2,0]]

array([ 2, 10, 11,  5])

In [186]:
x = np.random.randint(1,30,(2,3,4))
x

array([[[19,  2, 16,  7],
        [ 4,  3, 25, 22],
        [ 6,  9,  8, 21]],

       [[ 1,  7, 10, 24],
        [12, 10,  5, 12],
        [ 3, 11, 14, 16]]])

In [197]:
x[0][1][2]

25

In [201]:
x[1][1][0]

12

In [203]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [227]:
x+4

array([ 5,  6,  7,  8,  9, 10])

In [229]:
np.add(x,4)

array([ 5,  6,  7,  8,  9, 10])

In [231]:
np.subtract(x,6)

array([-5, -4, -3, -2, -1,  0])

In [220]:
x-5

array([-4, -3, -2, -1,  0,  1])

In [214]:
x+2

array([3, 4, 5, 6, 7, 8])

In [216]:
x/3

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

In [218]:
x*4

array([ 4,  8, 12, 16, 20, 24])

In [233]:
np.multiply(x,2)

array([ 2,  4,  6,  8, 10, 12])

In [235]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [237]:
min(x)

1

In [239]:
max(x)

6

In [241]:
np.min(x)

1

In [243]:
np.max(x)

6

In [247]:
x.sum()

21

In [249]:
np.sum(x)

21

In [255]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

In [257]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [259]:
np.square(x)

array([ 1,  4,  9, 16, 25, 36])

In [265]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [16]:
x = np.random.randint(1,30,(4,3))

In [18]:
x

array([[24, 23, 27],
       [16, 14, 10],
       [21, 20, 24],
       [ 1, 24, 15]])

In [21]:
x.max(axis = 0)  # col

array([24, 24, 27])

In [23]:
x.max(axis = 1)  # row

array([27, 16, 24, 24])

In [25]:
x.sum(axis = 1)

array([74, 40, 65, 40])

In [280]:
np.max(x)

29

In [282]:
x.sum()

188

In [284]:
x.max()

29

In [27]:
x = np.random.randint(1,30,6)
x

array([26,  1, 12, 12,  1, 22])

In [29]:
y = np.random.randint(1,30,6)
y

array([15, 16, 29,  3,  4, 14])

In [31]:
x+y

array([41, 17, 41, 15,  5, 36])

In [33]:
x-y

array([ 11, -15, -17,   9,  -3,   8])

In [35]:
np.add(x,y)

array([41, 17, 41, 15,  5, 36])

In [39]:
np.multiply(x,y)

array([390,  16, 348,  36,   4, 308])

In [41]:
x*y

array([390,  16, 348,  36,   4, 308])

In [48]:
x/y

array([1.73333333, 0.0625    , 0.4137931 , 4.        , 0.25      ,
       1.57142857])

In [50]:
x**y

array([-637370368,          1,          0,       1728,          1,
       -895336448])

In [52]:
x//y

array([1, 0, 0, 4, 0, 1])

In [65]:
x = np.random.randint(1,30,(3,3))
x

array([[11,  3, 19],
       [10,  1, 18],
       [ 8, 23, 15]])

In [67]:
y = np.random.randint(1,30,(3,3))
y

array([[ 5, 26,  4],
       [11,  9,  5],
       [ 9, 21, 11]])

In [69]:
x+y

array([[16, 29, 23],
       [21, 10, 23],
       [17, 44, 26]])

In [71]:
x-y

array([[  6, -23,  15],
       [ -1,  -8,  13],
       [ -1,   2,   4]])

In [73]:
x*y

array([[ 55,  78,  76],
       [110,   9,  90],
       [ 72, 483, 165]])

In [89]:
x = np.random.randint(1,10,(2,2))
x

array([[3, 2],
       [5, 1]])

In [111]:
y = np.random.randint(1,10,(2,2))
y

array([[5, 6],
       [8, 7]])

In [113]:
x@y

array([[31, 32],
       [33, 37]])

In [115]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [121]:
y = np.array([[4,5],[6,7]])
y

array([[4, 5],
       [6, 7]])

In [123]:
x@y

array([[16, 19],
       [36, 43]])

In [197]:
x = np.random.randint(1,10,(1,3))
y = np.random.randint(1,10,(3,1))


In [199]:
x

array([[7, 6, 8]])

In [201]:
y

array([[2],
       [7],
       [7]])

In [203]:
x@y

array([[112]])

In [187]:
# dot product possible ?

# m1 -> r1 x c1
# m2 -> r2 x c2

# c1 == r2  

# output ->  r1 x c2

In [205]:
# types of loops in array

In [207]:
# basic loop
# nditer
# ndenumerate

In [221]:
x = np.random.randint(1,30,5)
x

array([ 4, 12, 14,  8, 16])

In [223]:
for i in x:
    print(i)

4
12
14
8
16


In [234]:
x = np.random.randint(1,30,(3,3))
x

array([[27, 13, 19],
       [14, 22, 15],
       [12,  1, 18]])

In [238]:
for i in x:
    for j in i:
        print(j)

27
13
19
14
22
15
12
1
18


In [240]:
x = np.random.randint(1,30,(2,3,3))
x

array([[[25, 15, 19],
        [23, 19, 28],
        [20, 29, 21]],

       [[ 5,  5, 25],
        [14,  2, 28],
        [ 2,  2,  1]]])

In [259]:
for i in x:
    for j in i :
        for k in j:
            print(k)

25
15
19
23
19
28
20
29
21
5
5
25
14
2
28
2
2
1


In [262]:
x = np.random.randint(1,30,(3,3))
x

array([[16, 29, 27],
       [ 4, 27,  2],
       [20,  5, 29]])

In [269]:
for i in np.nditer(x):
    print(i)

16
29
27
4
27
2
20
5
29


In [271]:
x = np.random.randint(1,30,(2,3,3))
x

array([[[28, 20, 22],
        [19, 18,  9],
        [14, 14,  7]],

       [[ 4, 21,  7],
        [23, 20,  3],
        [28,  9, 18]]])

In [275]:
for i in np.nditer(x):
    print(i)

28
20
22
19
18
9
14
14
7
4
21
7
23
20
3
28
9
18


In [280]:
# ndenumerate

In [287]:
x = np.random.randint(1,30,(3,3))
x

array([[12,  8,  7],
       [14,  4,  5],
       [ 3, 26, 10]])

In [296]:
for i  , j in np.ndenumerate(x):
    print(i ,"---", j)

(0, 0) --- 12
(0, 1) --- 8
(0, 2) --- 7
(1, 0) --- 14
(1, 1) --- 4
(1, 2) --- 5
(2, 0) --- 3
(2, 1) --- 26
(2, 2) --- 10


In [298]:
x = np.random.randint(1,30,(2,3,3))
x

array([[[ 9, 21, 11],
        [18, 24, 18],
        [ 5, 24, 21]],

       [[23, 23, 19],
        [18, 26, 19],
        [ 7,  2,  8]]])

In [303]:
for i  , j in np.ndenumerate(x):
    print(i ,"---", j)

(0, 0, 0) --- 9
(0, 0, 1) --- 21
(0, 0, 2) --- 11
(0, 1, 0) --- 18
(0, 1, 1) --- 24
(0, 1, 2) --- 18
(0, 2, 0) --- 5
(0, 2, 1) --- 24
(0, 2, 2) --- 21
(1, 0, 0) --- 23
(1, 0, 1) --- 23
(1, 0, 2) --- 19
(1, 1, 0) --- 18
(1, 1, 1) --- 26
(1, 1, 2) --- 19
(1, 2, 0) --- 7
(1, 2, 1) --- 2
(1, 2, 2) --- 8


In [307]:
x = np.random.randint(1,30,(3,3))
x

array([[10, 18, 15],
       [ 7, 22, 13],
       [ 3, 20,  4]])

In [321]:
for i in range(len(x)):
    for j in range(len(x[i])):
        print(i,j,  "----" , x[i][j])

0 0 ---- 10
0 1 ---- 18
0 2 ---- 15
1 0 ---- 7
1 1 ---- 22
1 2 ---- 13
2 0 ---- 3
2 1 ---- 20
2 2 ---- 4


In [338]:
x = np.random.randint(1,30,(3,3))
x

array([[ 5, 23, 18],
       [13, 27,  4],
       [ 8, 20,  5]])

In [340]:
x

array([[ 5, 23, 18],
       [13, 27,  4],
       [ 8, 20,  5]])

In [351]:
s = 0
for i  , j in np.ndenumerate(x):
    if i[0] == i[1]:
        s = s+j
s

37

In [353]:
x = np.random.randint(1,30,(5,5))
x

array([[12, 26, 26, 28,  7],
       [24, 12, 25,  8, 12],
       [ 8, 12, 23, 16,  7],
       [ 2, 23, 28,  5, 24],
       [26, 24, 22,  4, 12]])

In [34]:
x = np.random.randint(1,30,7)
x

array([20,  7, 26, 11,  8, 16,  5])

In [22]:
# argmin - return index of min elemnt
# argmax - return index of max elemnt

In [36]:
x.argmin()

6

In [38]:
x.argmax()

2

In [50]:
x = np.random.randint(1,70,(5,4))
x

array([[68, 39, 12, 61],
       [29, 31, 15, 68],
       [39, 35, 22, 69],
       [54, 27, 68, 59],
       [52, 45, 29, 45]])

In [52]:
x.argmin(axis = 0)

array([1, 3, 0, 4], dtype=int64)

In [54]:
x.argmin(axis = 1)

array([2, 2, 2, 1, 2], dtype=int64)

In [56]:
# concatenation

In [91]:
# 1d -> 1d + 1d = 1d

In [82]:
x = np.random.randint(1,40,6)
x

array([35, 19, 20, 13, 21, 38])

In [84]:
y = np.random.randint(1,40,6)
y

array([32, 23, 23,  7,  9, 37])

In [89]:
np.concatenate((x,y))

array([35, 19, 20, 13, 21, 38, 32, 23, 23,  7,  9, 37])

In [113]:
# 2-d + 2d -> 2d

In [102]:
x = np.random.randint(1,40,(3,3))
x

array([[22,  5, 32],
       [39, 38, 31],
       [23,  9, 22]])

In [104]:
y = np.random.randint(1,40,(3,3))
y

array([[30, 33, 25],
       [ 2, 28,  6],
       [16, 13,  3]])

In [125]:
# axis = None -> first it convert both array in 1 d thn it will prfrm concatenatn

In [123]:
np.concatenate((x,y) , axis = None)

array([22,  5, 32, 39, 38, 31, 23,  9, 22, 30, 33, 25,  2, 28,  6, 16, 13,
        3])

In [121]:
np.concatenate((x,y) , axis = 1)  # horizntl

array([[22,  5, 32, 30, 33, 25],
       [39, 38, 31,  2, 28,  6],
       [23,  9, 22, 16, 13,  3]])

In [119]:
np.concatenate((x,y) , axis = 0)  # vertical

array([[22,  5, 32],
       [39, 38, 31],
       [23,  9, 22],
       [30, 33, 25],
       [ 2, 28,  6],
       [16, 13,  3]])

In [153]:
x = np.random.randint(1,40,(3,3))
y = np.random.randint(1,40,(4,3))


In [155]:
x

array([[38, 29,  5],
       [33, 11, 29],
       [35,  7, 30]])

In [157]:
y

array([[31,  4, 19],
       [ 5, 38, 30],
       [28,  7,  8],
       [12, 11, 24]])

In [165]:
np.concatenate((x,y) , axis = 0)

array([[38, 29,  5],
       [33, 11, 29],
       [35,  7, 30],
       [31,  4, 19],
       [ 5, 38, 30],
       [28,  7,  8],
       [12, 11, 24]])

In [167]:
x = np.random.randint(1,40,(2,3,3))
y = np.random.randint(1,40,(2,3,3))


In [169]:
x

array([[[29, 26, 16],
        [28,  5, 22],
        [20, 18, 24]],

       [[26, 11,  6],
        [34,  2, 24],
        [19, 33,  2]]])

In [171]:
y

array([[[17, 38, 31],
        [ 5, 12, 26],
        [37, 20, 21]],

       [[34, 39, 25],
        [27, 30, 26],
        [16, 28, 15]]])

In [192]:
np.concatenate((x,y) , axis = 2)

array([[[29, 26, 16, 17, 38, 31],
        [28,  5, 22,  5, 12, 26],
        [20, 18, 24, 37, 20, 21]],

       [[26, 11,  6, 34, 39, 25],
        [34,  2, 24, 27, 30, 26],
        [19, 33,  2, 16, 28, 15]]])

In [190]:
np.concatenate((x,y) , axis = 1)

array([[[29, 26, 16],
        [28,  5, 22],
        [20, 18, 24],
        [17, 38, 31],
        [ 5, 12, 26],
        [37, 20, 21]],

       [[26, 11,  6],
        [34,  2, 24],
        [19, 33,  2],
        [34, 39, 25],
        [27, 30, 26],
        [16, 28, 15]]])

In [188]:
np.concatenate((x,y) , axis = 0)

array([[[29, 26, 16],
        [28,  5, 22],
        [20, 18, 24]],

       [[26, 11,  6],
        [34,  2, 24],
        [19, 33,  2]],

       [[17, 38, 31],
        [ 5, 12, 26],
        [37, 20, 21]],

       [[34, 39, 25],
        [27, 30, 26],
        [16, 28, 15]]])

In [233]:
# stacking

# 1d + 1d -> 2d

In [277]:
x = np.random.randint(1,40,6)
y = np.random.randint(1,40,6)

In [279]:
x

array([33, 32,  2, 26,  7, 22])

In [281]:
y

array([ 2,  7,  3,  5, 15, 10])

In [283]:
np.concatenate((x,y))

array([33, 32,  2, 26,  7, 22,  2,  7,  3,  5, 15, 10])

In [288]:
np.stack((x,y) , axis = 0)

array([[33, 32,  2, 26,  7, 22],
       [ 2,  7,  3,  5, 15, 10]])

In [292]:
np.stack((x,y) , axis = 1)

array([[33,  2],
       [32,  7],
       [ 2,  3],
       [26,  5],
       [ 7, 15],
       [22, 10]])

In [261]:
# 2d + 2d = 3d

In [294]:
x = np.random.randint(1,40,(3,3))
y = np.random.randint(1,40,(3,3))

In [296]:
x

array([[26, 15,  9],
       [14, 35, 10],
       [28,  6, 16]])

In [298]:
y

array([[32, 35, 32],
       [ 3,  3, 38],
       [ 9,  8,  2]])

In [307]:
# np.concatenate((x,y))

In [300]:
np.stack((x,y))

array([[[26, 15,  9],
        [14, 35, 10],
        [28,  6, 16]],

       [[32, 35, 32],
        [ 3,  3, 38],
        [ 9,  8,  2]]])

In [309]:
np.stack((x,y) , axis = 1)

array([[[26, 15,  9],
        [32, 35, 32]],

       [[14, 35, 10],
        [ 3,  3, 38]],

       [[28,  6, 16],
        [ 9,  8,  2]]])

In [311]:
np.stack((x,y) , axis = 2)

array([[[26, 32],
        [15, 35],
        [ 9, 32]],

       [[14,  3],
        [35,  3],
        [10, 38]],

       [[28,  9],
        [ 6,  8],
        [16,  2]]])