In [7]:
import numpy as np

In [8]:
x=np.random.randint(1,30,(4,3))
x

array([[11, 17, 23],
       [24, 13, 26],
       [ 4, 25,  1],
       [17,  2,  2]], dtype=int32)

In [9]:
x[1]

array([24, 13, 26], dtype=int32)

In [10]:
x[1][0]

np.int32(24)

In [14]:
y=np.random.randint(1,100,(10,10))
y

array([[35, 72,  5, 59, 43, 24, 75, 51, 79, 86],
       [54, 40, 27, 93, 35, 15, 15,  1, 56, 82],
       [28, 78, 45, 29, 32, 49, 37, 30, 94, 61],
       [42, 75, 60, 69, 71, 16, 92, 49, 36, 53],
       [66, 90, 92, 87, 76, 12, 57, 61, 42, 80],
       [49, 97, 17, 63, 24, 87, 13, 23, 73, 46],
       [92, 89, 21, 68, 13, 54, 17, 99, 61, 39],
       [71, 19, 15,  4, 76, 76, 81, 44, 72, 72],
       [17, 21, 24, 17, 35, 26, 89, 63, 29, 60],
       [67, 24, 52, 21, 36, 82, 35, 29, 90, 83]], dtype=int32)

In [15]:
y[7:, [2,6,8]]

array([[15, 81, 72],
       [24, 89, 29],
       [52, 35, 90]], dtype=int32)

In [18]:
t=np.random.randint(1,30,7)
t

array([ 7, 12, 13, 23, 17, 22, 27], dtype=int32)

In [21]:
x[[0,2,3]]

array([[11, 17, 23],
       [ 4, 25,  1],
       [17,  2,  2]], dtype=int32)

In [24]:

s=np.arange(1,17).reshape(4,4)
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
s[[2,],[1,]]

array([10])