In [3]:
import numpy as np

In [8]:
x=np.random.randint(1,30,(4,3))
x

array([[11, 17, 23],
       [24, 13, 26],
       [ 4, 25,  1],
       [17,  2,  2]], dtype=int32)

In [9]:
x[1]

array([24, 13, 26], dtype=int32)

In [10]:
x[1][0]

np.int32(24)

In [14]:
y=np.random.randint(1,100,(10,10))
y

array([[35, 72,  5, 59, 43, 24, 75, 51, 79, 86],
       [54, 40, 27, 93, 35, 15, 15,  1, 56, 82],
       [28, 78, 45, 29, 32, 49, 37, 30, 94, 61],
       [42, 75, 60, 69, 71, 16, 92, 49, 36, 53],
       [66, 90, 92, 87, 76, 12, 57, 61, 42, 80],
       [49, 97, 17, 63, 24, 87, 13, 23, 73, 46],
       [92, 89, 21, 68, 13, 54, 17, 99, 61, 39],
       [71, 19, 15,  4, 76, 76, 81, 44, 72, 72],
       [17, 21, 24, 17, 35, 26, 89, 63, 29, 60],
       [67, 24, 52, 21, 36, 82, 35, 29, 90, 83]], dtype=int32)

In [15]:
y[7:, [2,6,8]]

array([[15, 81, 72],
       [24, 89, 29],
       [52, 35, 90]], dtype=int32)

In [18]:
t=np.random.randint(1,30,7)
t

array([ 7, 12, 13, 23, 17, 22, 27], dtype=int32)

In [21]:
x[[0,2,3]]

array([[11, 17, 23],
       [ 4, 25,  1],
       [17,  2,  2]], dtype=int32)

In [24]:

s=np.arange(1,17).reshape(4,4)
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [28]:
s[[2,],[1,]]

array([10])

In [11]:
# x=np.random.randint(1,40,(1,2,3))
x=np.random.randint(1,40,(8,9))
print(x)

[[33 29  8 10 12  5 28 36 13]
 [38 27 28  9 11 10 10  1 39]
 [17  6  7  2 15 27 35 12 15]
 [23 18 28 22 19  2 31 21 18]
 [33 35 29 36 18 33 17 17 14]
 [ 4 37  7 18 21 19  3 19 17]
 [16 26 23 11 15 13  5 24 33]
 [ 7 35 13 38 14  2  3 26  2]]


In [12]:
x[0][1]

29

In [21]:
x3=np.random.randint(1,30,7)
print(x)

[16  3  4 23 19  1 12]


In [22]:
#argmin -> 
x3.argmin()


3

In [ ]:
# argmax
x3.argmax()

In [27]:
# concatenationabs
x2=np.random.randint(1,40,6)
print(x2)

[19  5 23  1 13 15]


In [28]:
y2 = np.random.randint(1,40,6)
print(y2)

[11 36 38  4 32  1]


In [29]:
np.concatenate((x2,y2))

array([19,  5, 23,  1, 13, 15, 11, 36, 38,  4, 32,  1])

In [30]:
# 2d + 2d -> 2d

x4 = np.random.randint(1,40,(3,3))
x4

array([[19,  7, 20],
       [24,  2, 21],
       [36, 26, 12]])

In [31]:
y4 =  np.random.randint(1,40,(3,3))
y4

array([[21, 25,  3],
       [ 1, 24,  2],
       [38, 14, 34]])

In [32]:
np.concatenate((x4,y4))

array([[19,  7, 20],
       [24,  2, 21],
       [36, 26, 12],
       [21, 25,  3],
       [ 1, 24,  2],
       [38, 14, 34]])

In [5]:
# axis =None -? first it convert both array in 1 d then it will perform concatenatiionabs

# np.concatenate((x4,y4), axis="0")

In [ ]:
# stacking 


In [6]:
x5=np.random.randint(1,40,6)
print(x5)
y5=np.random.randint(1,40,6)
print(y5)

[14  4  3 33 21  5]
[12 31 11  3 20 16]


In [7]:
np.stack((x5,y5))

array([[14,  4,  3, 33, 21,  5],
       [12, 31, 11,  3, 20, 16]])

In [8]:
x6 = np.random.randint(1,40,(3,3))
print(x6)
y6 = np.random.randint(1,40,(3,3))
print(y6)

[[31 30  7]
 [17 11 22]
 [30 14 28]]
[[19 14 12]
 [22 35 32]
 [28 25 16]]


In [18]:
np.stack((x6,y6), axis=1)

array([[[31, 30,  7],
        [19, 14, 12]],

       [[17, 11, 22],
        [22, 35, 32]],

       [[30, 14, 28],
        [28, 25, 16]]])