In [10]:
import numpy as np
import time

In [12]:
# execution pPermissionError
size = 1_000_00

# python list 
py_list=list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python List Time = {end-start} seconds")

# numpy arrays 
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr**2
end = time.time()
print(f"Numpy Array Time = {end-start}seconds")


Python List Time = 0.17278027534484863 seconds
Numpy Array Time = 0.003197908401489258seconds


In [16]:
# memory 
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy array size = {np_arr.nbytes} bytes")

python list size = 80005600000 bytes
Numpy array size = 400000 bytes


In [22]:
# create - from lists 
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2= np.array([1,2,3,4,5,"abhishek"])
print(arr2, type(arr2),arr2.dtype, arr2.shape)

arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D , arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
['1' '2' '3' '4' '5' 'abhishek'] <class 'numpy.ndarray'> <U11 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
