In [2]:
import numpy as np
import time

In [12]:
# execution pPermissionError
size = 1_000_00

# python list 
py_list=list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python List Time = {end-start} seconds")

# numpy arrays 
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr**2
end = time.time()
print(f"Numpy Array Time = {end-start}seconds")


Python List Time = 0.17278027534484863 seconds
Numpy Array Time = 0.003197908401489258seconds


In [16]:
# memory 
import sys

print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"Numpy array size = {np_arr.nbytes} bytes")

python list size = 80005600000 bytes
Numpy array size = 400000 bytes


In [22]:
# create - from lists 
arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2= np.array([1,2,3,4,5,"abhishek"])
print(arr2, type(arr2),arr2.dtype, arr2.shape)

# matrix
arr2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2D , arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
['1' '2' '3' '4' '5' 'abhishek'] <class 'numpy.ndarray'> <U11 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [18]:
# create Numpy Arrays - from scratch

print("Zeros - all prefill with 0s")
arr1 = np.zeros((3,4), dtype="int64")
print(arr1,arr1.shape)

print("ones - all prefill with 1s")
arr2 = np.ones((3,3))
print(arr2,arr2.shape)

# 1D array 
arr3 = np.ones((2,))
print(arr3, arr3.shape)

print("full - fill with particular value")
arr4 = np.full((3,3), 5)
print(arr4,arr4.shape)

print("eye - used for identity matrix")
arr5 = np.eye((2))
print(arr5,arr5.shape)

print("arange - same as range function there are three parameters , start-stop-step")
arr6 = np.arange(1,11,1)
print(arr6,arr6.shape)

print("linspace - evenly space array")
arr7 = np.linspace(1,100,6)
print(arr7,arr7.shape)




Zeros - all prefill with 0s
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] (3, 4)
ones - all prefill with 1s
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[1. 1.] (2,)
full - fill with particular value
[[5 5 5]
 [5 5 5]
 [5 5 5]] (3, 3)
eye - used for identity matrix
[[1. 0.]
 [0. 1.]] (2, 2)
arange - same as range function there are three parameters , start-stop-step
[ 1  2  3  4  5  6  7  8  9 10] (10,)
linspace - evenly space array
[  1.   20.8  40.6  60.4  80.2 100. ] (6,)


In [22]:
# operations on arrays

arr= np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D => 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [35]:
# Indexing on np arrays

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, arr.shape)

# Normal Indexing
print(arr[0][1])

arr1 = np.array([1,2,3,4,5,6])

# Fancy Indexing
idx = [0,3,5]
print(arr1[idx])

# Boolean Indexing
print(arr1[arr1>2])
print(arr1[arr1%2==0])
print(arr1[arr1%2!=0])


[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
2
[1 4 6]
[3 4 5 6]
[2 4 6]
[1 3 5]


In [40]:
# Slicing on arrays

arr9= np.array([1,2,3,4,5,6])
print(arr9[1:4]) #start, end, ending
print(arr9[1:])
print(arr9[:4])
print(arr9[::])

[2 3 4]
[2 3 4 5 6]
[1 2 3 4]
[1 2 3 4 5 6]


In [46]:
# copy vs view
# list uses copy and numpy uses view of data

list1 = [1,2,3,4,5]
sub_list = list1[1:3]
print(sub_list)
sub_list[0] = 500
print(sub_list)
print(list1)

# # numpy array
# npy = np.array([1,2,3,4,5])
# sub_array = npy[1:3]
# print(sub_array)
# sub_array[0] = 500
# print(sub_array)
# print(npy)

# numpy array
npy = np.array([1,2,3,4,5])
sub_array = npy[1:3].copy()
print(sub_array)
sub_array[0] = 500
print(sub_array)
print(npy)

[2, 3]
[500, 3]
[1, 2, 3, 4, 5]
[2 3]
[500   3]
[1 2 3 4 5]


In [6]:
x = np.random.randint(1,30,(5,5))
print(x)

# min(x)

[[ 9 23 17 16 21]
 [ 3 13 14 18 17]
 [19 23 28 18  6]
 [21  9 26 20  8]
 [22 13 28  1  3]]
